# Generated by Django 5.1.5 on 2025-02-11 10:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chai_variety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='chais/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('kaisi', models.CharField(choices=[('ML', 'MASALA'), ('GR', 'GINGER'), ('BT', 'BLACK'), ('KW', 'KIWI'), ('EL', 'ELAICHI')], max_length=2)),
            ],
        ),
    ]
