# Generated by Django 5.1.5 on 2025-02-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chai_variety',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='chai_variety',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
